### ISSUE TITLE
Reintroduce JMoney helper for adding records to SpanLocal

### ISSUE THREAD

**Issue by ptravers** [Comcast/money#107]
JMoney is not currently available in the prospective 0.9 release. Not being available would cause breaking changes for Java users of Money.

**Comment by HaloFour** [comment]
I agree, it would be nice to have a Java-oriented bridge API back in Money.

However, I would like to explore a different API from the one that shipped with Money 0.8.x.  In our codebase I noticed a common anti-pattern when using money to manage spans manually:

```java
money.startSpan("my-span");
try {
    // do something here
} catch (Exception ex) {
    money.stopSpan(Result.failed());
} finally {
    money.close();
}
```

As `close` just calls `stopSpan(Result.success())` this results in the span being closed twice in the case of an exception.

As Money now only targets Java 8+ I think that any APIs could take advantage of newer language features to try to guide the developer to use Money correctly, specifically try-with-resources and/or lambdas.

**Comment by HaloFour** [comment]
Here's an example API based on a wrapper class I have already been working on for our project:

https://gist.github.com/HaloFour/0d5e0e0df75cba405e9e0407993cbe1b

**Comment by ptravers** [comment]
Hey Justin sorry I haven't taken care of this yet. Had a huge amount of work fall in my lap. I will do my best to get this done as soon as possible.

That sounds awesome. Does the AspectJ API provide a better way of achieving that same result? I was also wondering with in my limited understanding the limitations around lambda is it possible to have a trace function that takes a lambda?

**Comment by ptravers** [comment]
> Here's an example API based on a wrapper class I have already been working on for our project:
> 
> https://gist.github.com/HaloFour/0d5e0e0df75cba405e9e0407993cbe1b

sorry just saw this will take a look in a hour or so over lunch

**Comment by ptravers** [comment]
Ha nice that looks great. I was wondering though what the effect of hard deprecating the JMoney api would be. I feel like the gist represents a great additive change. I don't know if I would be in favour of dropping the existing API

**Comment by HaloFour** [comment]
@ptravers 

No worries, gives us the opportunities to explore other shapes to those APIs.  We do use the AspectJ API the majority of the time, but we do also manually create spans in those cases where either the aspect can't be applied by Spring (e.g. due to the method being non-public) or where we might want to have additional control (e.g. generating the name of the span based on parameters or a derived class name).

Yes, Java can handle trace APIs that accept lambdas, but there are additional considerations when it comes to checked exceptions.  Java also doesn't recognize the Scala "Function" classes to be functional interfaces and can't use the existing APIs.

**Comment by HaloFour** [comment]
I've submitted the following PR which adds the `JMoney` class back with the same API surface that it had in money 0.8.x and additional APIs supporting TWR and lambdas.

https://github.com/Comcast/money/pull/120

It could use more documentation but I wanted to get eyes on it first.

**Comment by hdzh** [comment]
@ptravers @paulcleary When will you release JMoney? We need that. Currently, we use 0.9.0 and copied over JMoney in our own code base. However, JMoney.record() somehow doesn't work well with @Traced in the same span name, logs the same span name with span success three times instead of once. Does it get a different tracer, referring to `Money.Environment().tracer()` in JMoney? Any idea?

**Comment by HaloFour** [comment]
@hdzh 

Are you experiencing that problem with the version of the `JMoney` source in the [referenced PR](https://github.com/Comcast/money/pull/120)?

**Comment by ptravers** [comment]
@hdzh I believe @paulcleary is the only one currently with release privileges. @paulcleary would you be comfortable with releasing 0.9.1 release to get out the bugfix?

**Comment by hdzh** [comment]
It looks like not JMoney issue, but somehow one span-name causes three different span-ids, and logs three times. I'm using 0.9.0. I didn't have the problem before when using 0.8.x.

**Comment by ptravers** [comment]
@hdzh sorry I misunderstood your comment. I will create a separate issue to resolve that.

**Comment by ptravers** [comment]
https://github.com/Comcast/money/issues/130

**Comment by ptravers** [comment]
@hdzh does this also occur on span failure? Can you provide any additional context about the instrumented code?
